name: $(Date:yyyyMMdd).$(Rev:-rrr)

trigger:
  batch: true
  branches:
    include:
    - master
    - features/*
    exclude:
    - features/experimental/*
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - master
    - features/*
    exclude:
    - features/experimental/*
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Download DotNetCore 2.1'
  inputs:
    packageType: 'sdk'
    version: '2.1.500'

- task: NuGetToolInstaller@0
  displayName: 'Download NuGet 4.9.3'
  inputs:
    versionSpec: '4.9.3'
    checkLatest: false

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: restore
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build multi-target framework project'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True

- task: CopyFiles@2
  displayName: 'Copy NuGet to artifacts directory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**\Release\*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: True

- task: NuGetCommand@2
  displayName: 'Push NuGet as prerelease $(Build.SourceBranch) $(Build.Reason)'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  inputs:
    command: restore
    restoreSolution: '$(solution)'

- task: NuGetCommand@2
  displayName: 'Push NuGet as official release'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: restore
    restoreSolution: '$(solution)'
