name: $(Date:yyyyMMdd)$(Rev:-rrr)

trigger:
  batch: true
  branches:
    include:
    - master
    exclude:
    - features/*
    - features/experimental/*
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - master
    - features/*
    exclude:
    - features/experimental/*
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '2'
  Minor: '0'
  Patch: '0'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install DotNetCore v2.1'
  inputs:
    packageType: 'sdk'
    version: '2.1.500'

- task: NuGetToolInstaller@0
  displayName: 'Install NuGet v4.9.3'
  inputs:
    versionSpec: '4.9.3'
    checkLatest: false

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: restore
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build multi-target framework project'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True

- task: NuGetCommand@2
  displayName: 'Pack prerelease NuGet from branch'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'Manual'), variables['nuget.publishPrerelease'])
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    packDestination: '$(Build.ArtifactStagingDirectory)\packages'

- task: PublishPipelineArtifact@0
  displayName: 'Publish prerelease NuGet as Pipeline Artifact'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'Manual'), variables['nuget.publishPrerelease'])
  inputs:
    artifactName: 'packages'
    targetPath: '$(Build.ArtifactStagingDirectory)\packages'

- task: CopyFiles@2
  displayName: 'Copy NuGet to artifacts directory'
  enabled: false
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**\Release\*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: True

- task: NuGetCommand@2
  displayName: 'Push NuGet as official release with version $(nugetVersion) from master'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  enabled: false
  inputs:
    command: restore
    restoreSolution: '$(solution)'
    #packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    #nuGetFeedType: external
    #publishFeedCredentials: '$(nuget.credentials)'
